spring:
  mail:
    default-encoding: UTF-8
    host:  smtp.gmail.com
    port: 587
    username: 3537184@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
      protocol: smtp
      test-connection: false
    servlet:
      multipart:
         max-file-size: 5MB
         max-request-size: 5MB